services:
  db:
    image: pgvector/pgvector:pg16
    container_name: science_news_db
    environment:
      POSTGRES_DB: science_news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: